<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PaymentRegistryService"
	targetNamespace="http://osb.tutorial.epam.com/PaymentRegistryService"
	xmlns:tns="http://osb.tutorial.epam.com/PaymentRegistryService"
	xmlns:reg="http://kz.cits.osb.com/test/registry" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl:types>
		<xsd:schema targetNamespace="http://osb.tutorial.epam.com/PaymentRegistryService">
			<xsd:import namespace="http://kz.cits.osb.com/test/registry"
				schemaLocation="../xsd/registry.xsd" />
		</xsd:schema>
	</wsdl:types>

	<!-- PARAMETERS -->
	<wsdl:message name="ForwardRegistry">
		<wsdl:part name="request" type="reg:regestryType" />
	</wsdl:message>
	<wsdl:message name="ForwardRegistryResponse">
		<wsdl:part name="response" type="xsd:string" />
	</wsdl:message>

	<!-- operations -->
	<wsdl:portType name="PaymentRegistryService">
		<wsdl:operation name="forwardRegistry">
			<wsdl:input message="tns:ForwardRegistry" />
			<wsdl:output message="tns:ForwardRegistryResponse" />
		</wsdl:operation>
		
	</wsdl:portType>

	<wsdl:binding name="PaymentRegistryServiceSOAP" type="tns:PaymentRegistryService">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="forwardRegistry">
			<soap:operation
				soapAction="http://osb.tutorial.epam.com/PaymentRegistryService/ForwardRegistry" />
			<wsdl:input>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://osb.tutorial.epam.com/PaymentRegistryService"
					use="encoded" />
			</wsdl:input>
			<wsdl:output>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://osb.tutorial.epam.com/PaymentRegistryService"
					use="encoded" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="PaymentRegistryService">
		<wsdl:port binding="tns:PaymentRegistryServiceSOAP" name="PaymentRegistryServiceSOAP">
			<soap:address location="http://to-be-defined-by-user" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
