<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="MessageService"
	targetNamespace="http://osb.tutorial.epam.com/MessageService"
	xmlns:tns="http://osb.tutorial.epam.com/MessageService" xmlns:test="http://kz.cits.osb.com/test/registry"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl:types>
		<xsd:schema targetNamespace="http://osb.tutorial.epam.com/MessageService">
			<xsd:import namespace="http://kz.cits.osb.com/test/registry"
				schemaLocation="../xsd/request.xsd" />
			<xsd:element name="SendMessage">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="request" type="test:requestType"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>

	<!-- PARAMETERS -->
	<!-- input parameter -->
	<wsdl:message name="SendMessageRequest">
		<wsdl:part element="tns:SendMessage" name="request" />
	</wsdl:message>
	<!-- return value -->
	<wsdl:message name="SendMessageResponse">
		<wsdl:part name="response" type="xsd:string" />
	</wsdl:message>
	<!-- operations -->
	<wsdl:portType name="MessageService">
		<wsdl:operation name="SendMessage">
			<wsdl:input message="tns:SendMessageRequest" />
			<wsdl:output message="tns:SendMessageResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="MessageServiceSOAP" type="tns:MessageService">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="SendMessage">
			<soap:operation
				soapAction="http://osb.tutorial.epam.com/MessageService/SendMessage" />
			<wsdl:input>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://osb.tutorial.epam.com/MessageService" use="encoded" />
			</wsdl:input>
			<wsdl:output>
				<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://osb.tutorial.epam.com/MessageService" use="encoded" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="MessageService">
		<wsdl:port binding="tns:MessageServiceSOAP" name="MessageServiceSOAP">
			<soap:address location="http://to-be-defined-by-user" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
